// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq1lbLbL3YJHt0YQdfP_Hb7-prCcHFMtI',
    appId: '1:267569417104:web:fc591b3aaeee5722f14115',
    messagingSenderId: '267569417104',
    projectId: 'praktek-dokter-app',
    authDomain: 'praktek-dokter-app.firebaseapp.com',
    storageBucket: 'praktek-dokter-app.appspot.com',
    measurementId: 'G-WCHJ23D3MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARvwcGcCbBLURfJfhvQjQyyCTonscWnFQ',
    appId: '1:267569417104:android:e16b8f1d4562b080f14115',
    messagingSenderId: '267569417104',
    projectId: 'praktek-dokter-app',
    storageBucket: 'praktek-dokter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClU9MYSy-_dt3V1mk5YpTDhqkbLqjmMhY',
    appId: '1:267569417104:ios:5db4c97d2e610469f14115',
    messagingSenderId: '267569417104',
    projectId: 'praktek-dokter-app',
    storageBucket: 'praktek-dokter-app.appspot.com',
    iosBundleId: 'com.example.flutterPraktekDokter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClU9MYSy-_dt3V1mk5YpTDhqkbLqjmMhY',
    appId: '1:267569417104:ios:cf6b244bc229ae44f14115',
    messagingSenderId: '267569417104',
    projectId: 'praktek-dokter-app',
    storageBucket: 'praktek-dokter-app.appspot.com',
    iosBundleId: 'com.example.flutterPraktekDokter.RunnerTests',
  );
}
